name: yak
description: A new Flutter project.

publish_to: "none"

version: 1.0.12+01001200

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  beamer: ^1.5.2
  bloc_test: ^9.1.0
  carousel_slider: ^4.1.1
  cuid:
    path: ../../development/cuid
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  drift: ^2.1.0
  dropdown_button2: ^1.7.2
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  firebase_core: ^1.21.0
  firebase_remote_config: ^2.0.15
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  flutter_inappwebview: ^5.4.3+7
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.1.4
  flutter_switch:
    path: ../../development/FlutterSwitch
  fluttertoast: ^8.0.9
  formz: ^0.4.1
  google_fonts: ^3.0.1

  google_mlkit_text_recognition: ^0.4.0
  html: ^0.15.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  import_sorter: ^4.6.0
  intl: ^0.17.0
  kiwi: ^4.0.2
  logger: ^1.1.0
  mask_text_input_formatter: ^2.4.0
  mocktail: ^0.3.0
  package_info_plus: ^1.4.3+1
  path: ^1.8.2
  path_provider: ^2.0.10
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.2
  sqlite3_flutter_libs: ^0.5.7
  table_calendar:
    path: ../../development/table_calendar
  url_launcher: ^6.1.4
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^2.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/liver_lover.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: rixMGoL
      fonts:
        - asset: fonts/RixMGoL.ttf

    - family: rixMGoM
      fonts:
        - asset: fonts/RixMGoM.ttf

    - family: rixMGoB
      fonts:
        - asset: fonts/RixMGoB.ttf

    - family: rixMGoEB
      fonts:
        - asset: fonts/RixMGoEB.ttf

    - family: airbnb
      fonts:
        - asset: fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: fonts/AirbnbCerealMedium.ttf
          weight: 500
        - asset: fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: fonts/AirbnbCerealBlack.ttf
          weight: 900

    - family: IconDatas
      fonts:
        - asset: fonts/IconDatas.ttf
