name: yak
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  beamer: ^1.4.1+1
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  awesome_notifications: ^0.6.21
  # hydrated_bloc: ^8.1.0
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.7
  path_provider: ^2.0.10
  path: ^1.8.1
  logger: ^1.1.0
  kiwi: ^4.0.2
  dartz: ^0.10.1
  intl: ^0.17.0
  cuid:
    path: ../../development/cuid
  rxdart: ^0.27.4
  flutter_bloc: ^8.0.1
  mocktail: ^0.3.0
  formz: ^0.4.1
  mask_text_input_formatter: ^2.3.0
  flutter_inappwebview: ^5.4.3+7
  dio: ^4.0.6
  flutter_svg: ^1.1.0
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  flutter_speed_dial: ^6.0.0
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  drift_dev: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: rixMGo
      fonts:
        - asset: fonts/RixMGoL.ttf
          weight: 300
        - asset: fonts/RixMGoM.ttf
          weight: 500
        - asset: fonts/RixMGoB.ttf
          weight: 700
        - asset: fonts/RixMGoEB.ttf
          weight: 800

    - family: airbnb
      fonts:
        - asset: fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: fonts/AirbnbCerealMedium.ttf
          weight: 500
        - asset: fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: fonts/AirbnbCerealBlack.ttf
          weight: 900

    - family: IconDatas
      fonts:
        - asset: fonts/IconDatas.ttf
