name: yak
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  beamer: ^1.4.1+1
  carousel_slider: ^4.1.1
  cuid:
    path: ../../development/cuid
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  drift: ^1.6.0
  dropdown_button2: ^1.6.3
  equatable: ^2.0.3
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  flutter_inappwebview: ^5.4.3+7
  flutter_speed_dial: ^6.0.0
  flutter_svg: ^1.1.0
  flutter_switch:
    path: ../../development/FlutterSwitch
  formz: ^0.4.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  import_sorter: ^4.6.0
  intl: ^0.17.0
  kiwi: ^4.0.2
  logger: ^1.1.0
  mask_text_input_formatter: ^2.3.0
  mocktail: ^0.3.0
  path: ^1.8.1
  path_provider: ^2.0.10
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.2
  sqlite3_flutter_libs: ^0.5.7
  table_calendar:
    path: ../../development/table_calendar
  url_launcher: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^1.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: rixMGoL
      fonts:
        - asset: fonts/RixMGoL.ttf

    - family: rixMGoM
      fonts:
        - asset: fonts/RixMGoM.ttf

    - family: rixMGoB
      fonts:
        - asset: fonts/RixMGoB.ttf

    - family: rixMGoEB
      fonts:
        - asset: fonts/RixMGoEB.ttf

    - family: airbnb
      fonts:
        - asset: fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: fonts/AirbnbCerealBook.ttf
          weight: 400
        - asset: fonts/AirbnbCerealMedium.ttf
          weight: 500
        - asset: fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: fonts/AirbnbCerealExtraBold.ttf
          weight: 800
        - asset: fonts/AirbnbCerealBlack.ttf
          weight: 900

    - family: IconDatas
      fonts:
        - asset: fonts/IconDatas.ttf
